task_name: counterfactual_inpainting
logging_dir: /scratch/project_465001979/coin_training_logs/GAN/FINAL_EXPERIMENT_BALANCED

seed: 777
sample_interval: 50

n_epochs: 100
# epoch_steps: 800

experiment_name: TANH_MODIFICATION
checkpoint_freq: 1
eval_counter_freq: 1
apply_tanh_to_non_gen_imgs_in_eval: True
cf_gt_seg_mask_idx: 2
log_visualizations: false

compute_norms: False

dataset:
  kind: merged
  batch_size: 16
  img_size: [256, 256] # hxw
  use_sampler: True
  reset_sampler: True
  num_workers: 7
  imagenet_norm: False # mean=[0.5], std=[0.5]
  root_dir: null
  augs: [] # only resize and norm

  datasets:
    - kind: tuh
      root_dir: /projappl/project_465001111/ct_data/kidney
      split_dir: /users/lillemag/makatoo/coin_test/counterfactual-search/configs/THESIS_EXPERIMETNS/thesis_splits
      # TUH_LABEL_NAMES = {
      #     1: "kidney",
      #     2: "tumor",
      #     3: "cyst"
      # }
      scan_params:
        load_masks: True
        norm_scheme: &norm
          kind: ct
          rescale: True
          fingerprint_path: /users/lillemag/makatoo/coin_test/counterfactual-search/configs/TUH_LOSS_BALANCER/dataset_fingerprint.json
        slicing_direction: axial
        classes: ['empty', 'kidney', 'tumor', 'cyst']
        
        sampling_class: ['tumor']
        classify_labels: ['tumor']
        classify_labels_thresh: 1000

        # fetch only kidney slices in loaders that have masks with at least `filter_class_slices_thresh` non zero pixels
        filter_class_slices: ['kidney']
        filter_class_slices_thresh: 100

model:
  kind: inpainting_counterfactual_cgan
  ptb_based: True # perturbation based generator
  in_channels: 1
  gen_update_freq: 5
  adv_loss: mse
  lambda_adv: 1.0
  lambda_kl: 1.0
  lambda_rec: 0.0
  lambda_tv: 0.0005
  lambda_minc: 0.0
  # precision: 16-mixed
  precision: '32'

  apply_tanh_to_non_gen_imgs: True # apply tanh to non-gen images
  
  cyclic_rec: True

  original_discriminator: True

  
  # optimizers' parameters
  lr: 0.0002
  b1: 0.0
  b2: 0.999
  
  # default setting
  # encoder returns features [block_1(x), block_2(block_1(x)), ..., block_N(...)]
  enc_params:
    downsample_scales: [2, 2, 2, 2, 2]
    out_channels: [64, 128, 256, 512, 1024]
    use_snconv: false

  gen_params:
    upsample_scales: [2, 2, 2, 2, 2]
    out_channels: [1024, 512, 256, 128, 64]
    upsample_kind: bilinear
    use_snconv: false
    # indices are specifided w.r.t bottleneck (index=0) and upwards
    skip_conn: [1, 2, 3, 4]

  disc_params:
    downsample_scales: [2, 2, 2, 2, 2]
    out_channels: [64, 128, 256, 512, 1024]


  use_conditioning: true # use cGAN
  # counterfactual parameters
  num_bins: 2 # number of discrete bins into which posterior probabilities are sorted
  explain_class_idx: 0 # normal/not-normal kidneys

  # classifier parameters
  classifier_kind: efficientnet_v2_s
  n_classes: 1 # number of classes in the classifier
  classifier_ckpt: /scratch/project_465001979/coin_training_logs/classification/FINAL_EXPERIMENT_BALANCED/efficientnet_v2_s-May-05-2025_04+13PM-fde0568-OG_COIN_CLASSIFIER/checkpoints/checkpoint_-2.pth
